exports.seed = async (knex) => {
  await knex('productGallery').del();
  const products = await knex('product');
  const getId = (slug) => products.find((product) => product.slug === slug).id;

  return knex('productGallery').insert([
    {
      mobile: '/media/products/xx59-headphones/mobile/xx59-headphones-gallery-1.jpg',
      tablet: '/media/products/xx59-headphones/tablet/xx59-headphones-gallery-1.jpg',
      desktop: '/media/products/xx59-headphones/desktop/xx59-headphones-gallery-1.jpg',
      description: 'Woman jamming to music wearing XX59 Headphones',
      order: 1,
      productId: getId('xx59-headphones'),
    },
    {
      mobile: '/media/products/xx59-headphones/mobile/xx59-headphones-gallery-2.jpg',
      tablet: '/media/products/xx59-headphones/tablet/xx59-headphones-gallery-2.jpg',
      desktop: '/media/products/xx59-headphones/desktop/xx59-headphones-gallery-2.jpg',
      description: 'Four books wearing XX59 Headphones',
      order: 2,
      productId: getId('xx59-headphones'),
    },
    {
      mobile: '/media/products/xx59-headphones/mobile/xx59-headphones-gallery-3.jpg',
      tablet: '/media/products/xx59-headphones/tablet/xx59-headphones-gallery-3.jpg',
      desktop: '/media/products/xx59-headphones/desktop/xx59-headphones-gallery-3.jpg',
      description: 'Woman dangling XX59 Headphones on her pointer finger',
      order: 3,
      productId: getId('xx59-headphones'),
    },
    {
      mobile: '/media/products/xx99-mark-i-headphones/mobile/xx99-mark-i-headphones-gallery-1.jpg',
      tablet: '/media/products/xx99-mark-i-headphones/tablet/xx99-mark-i-headphones-gallery-1.jpg',
      desktop: '/media/products/xx99-mark-i-headphones/desktop/xx99-mark-i-headphones-gallery-1.jpg',
      description: 'XX99 Mark I Headphones hanging from a microphone',
      order: 1,
      productId: getId('xx99-mark-i-headphones'),
    },
    {
      mobile: '/media/products/xx99-mark-i-headphones/mobile/xx99-mark-i-headphones-gallery-2.jpg',
      tablet: '/media/products/xx99-mark-i-headphones/tablet/xx99-mark-i-headphones-gallery-2.jpg',
      desktop: '/media/products/xx99-mark-i-headphones/desktop/xx99-mark-i-headphones-gallery-2.jpg',
      description: 'A shoe, a watch, and XX99 Mark I Headphones laying on a desk',
      order: 2,
      productId: getId('xx99-mark-i-headphones'),
    },
    {
      mobile: '/media/products/xx99-mark-i-headphones/mobile/xx99-mark-i-headphones-gallery-3.jpg',
      tablet: '/media/products/xx99-mark-i-headphones/tablet/xx99-mark-i-headphones-gallery-3.jpg',
      desktop: '/media/products/xx99-mark-i-headphones/desktop/xx99-mark-i-headphones-gallery-3.jpg',
      description: 'XX99 Mark I Headphones wrapped in lights',
      order: 3,
      productId: getId('xx99-mark-i-headphones'),
    },
    {
      mobile: '/media/products/xx99-mark-ii-headphones/mobile/xx99-mark-ii-headphones-gallery-1.jpg',
      tablet: '/media/products/xx99-mark-ii-headphones/tablet/xx99-mark-ii-headphones-gallery-1.jpg',
      desktop: '/media/products/xx99-mark-ii-headphones/desktop/xx99-mark-ii-headphones-gallery-1.jpg',
      description: 'Man listening to music with XX99 Mark II Headphones',
      order: 1,
      productId: getId('xx99-mark-ii-headphones'),
    },
    {
      mobile: '/media/products/xx99-mark-ii-headphones/mobile/xx99-mark-ii-headphones-gallery-2.jpg',
      tablet: '/media/products/xx99-mark-ii-headphones/tablet/xx99-mark-ii-headphones-gallery-2.jpg',
      desktop: '/media/products/xx99-mark-ii-headphones/desktop/xx99-mark-ii-headphones-gallery-2.jpg',
      description: 'A phone, a magazine, and XX99 Mark II Headphones laying on a table',
      order: 2,
      productId: getId('xx99-mark-ii-headphones'),
    },
    {
      mobile: '/media/products/xx99-mark-ii-headphones/mobile/xx99-mark-ii-headphones-gallery-3.jpg',
      tablet: '/media/products/xx99-mark-ii-headphones/tablet/xx99-mark-ii-headphones-gallery-3.jpg',
      desktop: '/media/products/xx99-mark-ii-headphones/desktop/xx99-mark-ii-headphones-gallery-3.jpg',
      description: 'XX99 Mark II Headphones against a black background',
      order: 3,
      productId: getId('xx99-mark-ii-headphones'),
    },
    {
      mobile: '/media/products/yx1-wireless-earphones/mobile/yx1-wireless-earphones-gallery-1.jpg',
      tablet: '/media/products/yx1-wireless-earphones/tablet/yx1-wireless-earphones-gallery-1.jpg',
      desktop: '/media/products/yx1-wireless-earphones/desktop/yx1-wireless-earphones-gallery-1.jpg',
      description: 'Zoomed in on YX1 Wireless Earphones laying on soft fabric',
      order: 1,
      productId: getId('yx1-wireless-earphones'),
    },
    {
      mobile: '/media/products/yx1-wireless-earphones/mobile/yx1-wireless-earphones-gallery-2.jpg',
      tablet: '/media/products/yx1-wireless-earphones/tablet/yx1-wireless-earphones-gallery-2.jpg',
      desktop: '/media/products/yx1-wireless-earphones/desktop/yx1-wireless-earphones-gallery-2.jpg',
      description: 'YX1 Wireless Earphones laying in their charging station',
      order: 2,
      productId: getId('yx1-wireless-earphones'),
    },
    {
      mobile: '/media/products/yx1-wireless-earphones/mobile/yx1-wireless-earphones-gallery-3.jpg',
      tablet: '/media/products/yx1-wireless-earphones/tablet/yx1-wireless-earphones-gallery-3.jpg',
      desktop: '/media/products/yx1-wireless-earphones/desktop/yx1-wireless-earphones-gallery-3.jpg',
      description: 'YX1 Wireless Earphones and charging station laying on soft fabric',
      order: 3,
      productId: getId('yx1-wireless-earphones'),
    },
    {
      mobile: '/media/products/zx7-speaker/mobile/zx7-speaker-gallery-1.jpg',
      tablet: '/media/products/zx7-speaker/tablet/zx7-speaker-gallery-1.jpg',
      desktop: '/media/products/zx7-speaker/desktop/zx7-speaker-gallery-1.jpg',
      description: 'Zoomed in on the ZX7 Speaker cone',
      order: 1,
      productId: getId('zx7-speaker'),
    },
    {
      mobile: '/media/products/zx7-speaker/mobile/zx7-speaker-gallery-2.jpg',
      tablet: '/media/products/zx7-speaker/tablet/zx7-speaker-gallery-2.jpg',
      desktop: '/media/products/zx7-speaker/desktop/zx7-speaker-gallery-2.jpg',
      description: 'Man sitting at a media production station with ZX7 Speakers',
      order: 2,
      productId: getId('zx7-speaker'),
    },
    {
      mobile: '/media/products/zx7-speaker/mobile/zx7-speaker-gallery-3.jpg',
      tablet: '/media/products/zx7-speaker/tablet/zx7-speaker-gallery-3.jpg',
      desktop: '/media/products/zx7-speaker/desktop/zx7-speaker-gallery-3.jpg',
      description: 'Close up of a ZX7 Speaker on a table',
      order: 3,
      productId: getId('zx7-speaker'),
    },
    {
      mobile: '/media/products/zx9-speaker/mobile/zx9-speaker-gallery-1.jpg',
      tablet: '/media/products/zx9-speaker/tablet/zx9-speaker-gallery-1.jpg',
      desktop: '/media/products/zx9-speaker/desktop/zx9-speaker-gallery-1.jpg',
      description: 'Close up of the ZX9 Speaker\'s cone',
      order: 1,
      productId: getId('zx9-speaker'),
    },
    {
      mobile: '/media/products/zx9-speaker/mobile/zx9-speaker-gallery-2.jpg',
      tablet: '/media/products/zx9-speaker/tablet/zx9-speaker-gallery-2.jpg',
      desktop: '/media/products/zx9-speaker/desktop/zx9-speaker-gallery-2.jpg',
      description: 'ZX9 Speaker in a room surrounded by records and plants',
      order: 2,
      productId: getId('zx9-speaker'),
    },
    {
      mobile: '/media/products/zx9-speaker/mobile/zx9-speaker-gallery-3.jpg',
      tablet: '/media/products/zx9-speaker/tablet/zx9-speaker-gallery-3.jpg',
      desktop: '/media/products/zx9-speaker/desktop/zx9-speaker-gallery-3.jpg',
      description: 'Two ZX9 Speakers side by side on a white background',
      order: 3,
      productId: getId('zx9-speaker'),
    },
  ]);
};
